### ISSUE TITLE
@import font

### ISSUE THREAD

**Issue by fguisso** [Qualy-org/qualy-presenter#17]
Estou tendo um problema com o @import:

```
/*
* Css file to create the generic presentation
*/
@import "vendor/reveal"

/*
* In src/styl/reveal-themes have more themes !!
*/
@import "reveal-themes/blood"

/*
* In src/styl/highlight-themes have more awesome highlight-themes !!
*/
@import "highlight-themes/zenburn"
```

Quando o "vendor/reveal" esta na frente, o @import do tema não entra, agora se eu colocar o vendor por ultimo o @import funciona, mas ai algumas configs ficam acima do tema.

Fiz esse teste de trocar a ordem pq o antigo Reveal-boilerplate estava nessa ordem e funcionava bem.

Sera q é algum problema na minha maquina? pq eu testei o gh-pages do projeto e parece não dar @import na font que nem o meu fork.

**Comment by willianjusten** [comment]
Opa, irei dar uma analisada em breve, como ando muito cheio de coisas, posso demorar uns 2 dias ok.

**Comment by gofilipe** [comment]
É porque browsers só aceitam @import nas primeiras linhas do CSS. Minha solução foi gerar dois arquivos com pequenas alterações no paths.js e head.jade.

**Comment by willianjusten** [comment]
Solved this issue in #46c85284850c0ac09e8bab17d70fe7462aadbdc2
